# Global map definitions - loaded first due to alphabetical ordering
# Maps host to upstream application port
map $host $upstream_port {
    default 8069;  # Default to Odoo port
    emoment.tech 3000;
    rm.emoment.tech 8066;
    mm.emoment.tech 8065;
    od.emoment.tech 8069;
    nihonrice.com 3002;
    www.nihonrice.com 3002;
    cms.nihonrice.com 1338;
    emoment.io 3044;
    www.emoment.io 3044;
}

# Maps host to websocket/longpolling port
map $host $websocket_port {
    default 8072;  # Default to Odoo longpolling port
    od.emoment.tech 8072;
    #rm.emoment.tech 8073;
    #mm.emoment.tech 8074;
}
